CREATE DATABASE IF NOT EXISTS db_landing;
USE db_landing;

CREATE TABLE CONTACTANOS
(
	IDCON INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NOMCON VARCHAR(50),
    GMACON VARCHAR(50),
    CELCON CHAR(9),
	MENCON VARCHAR(300)
);

INSERT INTO CONTACTANOS 
	(NOMCON, GMACON, CELCON, MENCON)
VALUES
	('Antonio', 'antonio.12@gmail.com', '987654321', 'Quiero saber los pasos para matricular');
    
SELECT * FROM CONTACTANOS;